# Generated by Django 4.1 on 2023-11-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
            ],
        ),
    ]
